### ISSUE TITLE
Igh in image

### ISSUE THREAD

**Issue by Torteski** [2b-t/docker-realtime#5]
Hi @2b-t 
Thank you very much for the very extensive explanation. 
I was able to make get an realtime image running with a RT patched host and IGH installed on host within an hour .
I was wondering if it would be possible to include the IGH master in the image as well. 
As the IGH master runs on kernel modules can these be running in a container?
Have you tried anything like this and do you think this would be at all possible? 

Any advice is appreciated

**Comment by 2b-t** [comment]
Hi @Torteski 
I am glad it is helpful.
So far I did not have the need for it but I assume that it should be possible with the  [**`--cap-add=SYS_MODULE`** ](https://docs.docker.com/engine/reference/run/) flag. This allows the Docker container to **insert kernel modules into the kernel of the host system** but reduces encapsulation. The disadvantage of this is that an intruder might use this privilege to escape the container, see [e.g. here](https://blog.pentesteracademy.com/abusing-sys-module-capability-to-perform-docker-container-breakout-cf5c29956edd).

If this does not bother you, I would simply modify the Docker-Compose file adding the `SYS_MODULE` capability:
```
version: "3.9"
services:
  docker_realtime:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: realtime_docker
    tty: true
    cap_add:
      - SYS_MODULE
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
```
then add the [installation procedure](https://www.etherlab.org/download/ethercat/ethercat-1.5.2.pdf#page=89) at the end of the Dockerfile and see if that works. I do not have time to test today it but I can give it a try in the following days in case this does not work.
